{{- if and .Values.consolelink.enabled .Values.clusterDomain }}
---
apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: {{ .Values.namespace }}-docs
spec:
  href: "https://docs-{{ .Values.namespace }}.apps.{{ .Values.clusterDomain }}"
  location: ApplicationMenu
  text: Red Hat Offline Knowledge Portal
  applicationMenu:
    section: Red Hat Applications
    imageURL: data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxOTIuMyAxNDYiPjxwYXRoIGZpbGw9IiNlMDAiIGQ9Im0xMjgsODRjMTIuNSwwIDMwLjYtMi42IDMwLjYtMTcuNWExOS41MywxOS41MyAwIDAgMC0wLjMtMy40TDE1MC45LDMwLjdDMTQ5LjIsMjMuNiAxNDcuNywyMC4zIDEzNS4yLDE0LjEgMTI1LjUsOS4xIDEwNC40LDEgOTguMSwxIDkyLjIsMSA5MC41LDguNSA4My42LDguNSA3Ni45LDguNSA3MiwyLjkgNjUuNywyLjljLTYsMC05LjksNC4xLTEyLjksMTIuNSAwLDAtOC40LDIzLjctOS41LDI3LjJhNi4xNSw2LjE1IDAgMCAwLTAuMiwxLjljMCw5LjIgMzYuMywzOS40IDg0LjksMzkuNW0zMi41LTExLjRjMS43LDguMiAxLjcsOS4xIDEuNywxMC4xIDAsMTQtMTUuNywyMS44LTM2LjQsMjEuOEM3OSwxMDQuNSAzOC4xLDc3LjEgMzguMSw1OWExOC4zNSwxOC4zNSAwIDAgMSAxLjUtNy4zQzIyLjgsNTIuNSAxLDU1LjUgMSw3NC43IDEsMTA2LjIgNzUuNiwxNDUgMTM0LjYsMTQ1YzQ1LjMsMCA1Ni43LTIwLjUgNTYuNy0zNi43IDAtMTIuNy0xMS0yNy4xLTMwLjgtMzUuNyIvPjxwYXRoIGQ9Im0xNjAuNSw3Mi42YzEuNyw4LjIgMS43LDkuMSAxLjcsMTAuMSAwLDE0LTE1LjcsMjEuOC0zNi40LDIxLjhDNzksMTA0LjUgMzguMSw3Ny4xIDM4LjEsNTlhMTguMzUsMTguMzUgMCAwIDEgMS41LTcuM2wzLjctOS4xYTYuMTUsNi4xNSAwIDAgMC0wLjIsMS45YzAsOS4yIDM2LjMsMzkuNCA4NC45LDM5LjQgMTIuNSwwIDMwLjYtMi42IDMwLjYtMTcuNWExOS41MywxOS41MyAwIDAgMC0wLjMtMy40eiIvPjwvc3ZnPg==
{{- end }}
