---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs
  namespace: {{ .Values.namespace }}
  labels:
    app: docs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docs
  template:
    metadata:
      labels:
        app: docs
    spec:
      containers:
        - name: rhokp
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8443
              name: https
          env:
            - name: ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: rhokp-secret
                  key: access-key
          resources:
            requests:
              memory: "1Gi"
              cpu: "50m"
            limits:
              memory: "3Gi"
              cpu: "1"